set(_CATKIN_CURRENT_PACKAGE "player_testeves")
set(player_testeves_VERSION "0.0.0")
set(player_testeves_MAINTAINER "tiagoesteves <tiagoesteves@todo.todo>")
set(player_testeves_PACKAGE_FORMAT "1")
set(player_testeves_BUILD_DEPENDS "roscpp" "rospy" "std_msgs" "tf" "rwsfi2016_libs" "pcl_ros")
set(player_testeves_BUILD_EXPORT_DEPENDS "pcl_ros" "rwsfi2016_libs" "roscpp" "rospy" "std_msgs" "tf")
set(player_testeves_BUILDTOOL_DEPENDS "catkin")
set(player_testeves_BUILDTOOL_EXPORT_DEPENDS )
set(player_testeves_EXEC_DEPENDS "pcl_ros" "rwsfi2016_libs" "roscpp" "rospy" "std_msgs" "tf")
set(player_testeves_RUN_DEPENDS "pcl_ros" "rwsfi2016_libs" "roscpp" "rospy" "std_msgs" "tf")
set(player_testeves_TEST_DEPENDS )
set(player_testeves_DOC_DEPENDS )
set(player_testeves_DEPRECATED "")